### ISSUE TITLE
NS3 + ONOS Integration + BRITE Integration

### ISSUE THREAD

**Issue by ljerezchaves** [ljerezchaves/ofswitch13#41]
*Originally reported by* **Akin Soysal (Bitbucket: [akinsoysal](https://bitbucket.org/akinsoysal), GitHub: [akinsoysal](https://github.com/akinsoysal))**

----------------------------------------

Hello,

I have some bugfixes and some enhancements.

We are working on enhancing the ONOS SDN controller. Instead of Mininet I tried your ofswitch13 module. It took me sometime but I finally did manage to get it properly working by enhancing the code which I obtained after going through the step by step instructions under: 

http://www.lrc.ic.unicamp.br/ofswitch13/ofswitch13.pdf

- 1 bug in ONOS was that it was returning a preset prefix for the MAC address although the given MAC address in NS3 was 00:00:00:00:01. ONOS was giving xx:xx:xx:00:00:01.
- One enhancement was that with ONOS we were sending PACKET_OUT messages piggybacked to the openflow message.
- Then we wanted to work with bigger topologies, so I integrated BRITE topology helper within NS3 and also added some other examples.
- Next, I realized that although topology discovery of ONOS was fine with small topologies, with bigger topologies I was getting errors. The problem was that many switches were communicating with the ONOS controller through the same local bridge and when a tcp packet was segmented, ONOS could send another switch's packet in between and this would cause problems during packet parsing. So instead of keeping packet parsing elements as static members, I changed them to local variables so that the segmented packets would not be confused among switches.

I have added a lot of working examples under scratch/.

Best Regards,
Akın

----------------------------------------
- Bitbucket: https://bitbucket.org/ljerezchaves/ofswitch13-module/issue/41

**Comment by ggaybueh** [comment]
Hello ljerezchaves,

I am doing my research on intent based network and I want to simulate my experiment using ns3. How can I build ONOS controller in NS3?
