### ISSUE TITLE
Bug in packet_parse function on packets with Ethernet 802.3 header

### ISSUE THREAD

**Issue by DanielaSousa** [ljerezchaves/ofswitch13#43]
https://github.com/ljerezchaves/ofsoftswitch13/blob/23b81fff3b31f92ef365627f7bbf61167f2cf647/udatapath/packet_handle_std.c#L93

This line should be : 

    eth_type = ntohs(proto->eth_snap->snap_type);

Otherwise, next protocols are not processed.

**Comment by ljerezchaves** [comment]
Fixed in 0211d4e3b5bba4e564b0f9569fd6ae80d2eb69e8
