### ISSUE TITLE
Porting to ns 3.36

### ISSUE THREAD

**Issue by prototact** [ljerezchaves/ofswitch13#46]
Hi! 
Are there some general directions on how to port this module to ns 3.36 ?

**Comment by Fateme-Mazloomi** [comment]
Hi,

I want to integrate openflowswitch13 to NS3.36, Is there any direction?
Do I need to create Cmake files for openflowswitch13?

**Comment by Fateme-Mazloomi** [comment]
Hello Prototact,

Did you find a way for building ofswitch13 in NS3.36?
Thanks,

**Comment by prototact** [comment]
No, I am not using it in my simulations currently.

**Comment by ljerezchaves** [comment]
Hi guys. The new release (5.1.0) works with ns-3.36 and ns-3.37.
